# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^.*\.yaml\.j2$
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black

- repo: local
  hooks:

  - id: build
    name: Build Grammar
    entry: python src/build_grammar.py
    language: python
    files: ^src/.*$
    pass_filenames: false
    additional_dependencies:
    - "pyyaml"
    - "jinja2"

  - id: test
    name: Test Grammar
    entry: vscode-tmgrammar-test -g tests/markdown.tmLanguage.json -g syntaxes/myst.tmLanguage tests/*.txt
    language: node
    files: ^syntaxes/.*|tests/.*$
    pass_filenames: false
    additional_dependencies:
    - "vscode-tmgrammar-test"
